version: '3.9'

x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  webhook:
    container_name: node_health
    image: webhook:local
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_TARGET=${WEBHOOK_SRC_BUILD_TARGET:-$(git describe --tags $(git rev-list --tags --max-count=1))}
        - SRC_REPO=${WEBHOOK_SRC_REPO:-https://github.com/adnanh/webhook.git}
    stop_grace_period: 1m
    pull_policy: build
    ports:
      - "${LISTEN_ADDRESS:-0.0.0.0:9000}:9000"
    restart: unless-stopped
    environment: 
      - "CC_ADDRESS=${CC_ADDRESS}"
      - "CC_MIN_PEERS=${CC_MIN_PEERS:-10}"
      - "EC_ADDRESS=${EC_ADDRESS}"
      - "EC_MIN_PEERS=${EC_MIN_PEERS:-10}"
    volumes: 
      - "./webhook-scripts:/var/scripts:ro"
      - "./webhook-config:/config:ro"
    <<: *logging